version: "3.9"

services:
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
      target: final
    image: auth-service:latest
    container_name: auth-service
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=db
    volumes:
      - ./services/auth-service/internal/config/config.docker.yaml:/config/config.docker.yaml
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "grpc_health_probe", "-addr=:50051" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: auth-db
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U auth_user -d auth_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: streaming-platform-network

volumes:
  db-data:
    name: auth-db-data